server:
  port: 3344
spring:
  application:
    name: cloud-config-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lilinpo?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lilinpo/springcloud-config.git #git地址
          search-paths:
            - springcloud-config
      label: main
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: config3344
    prefer-ip-address: true